[project]
name = "production-grade-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.141.1",
    "langchain-community>=0.4.2",
    "langchain-openrouter>=0.2.8",
    "langgraph>=1.2.12",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "slowapi>=0.1.10",
    "uvicorn>=0.54.0",
]

[project.scripts]
production-grade-rag = "main:main"
